module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brandlight: "var(--brandlight)",
        brandprimary: "var(--brandprimary)",
        brandsecondary: "var(--brandsecondary)",
        errorbg: "var(--errorbg)",
        errorcontent: "var(--errorcontent)",
        errordark: "var(--errordark)",
        issuebg: "var(--issuebg)",
        issuecontent: "var(--issuecontent)",
        neutralbg: "var(--neutralbg)",
        neutralcontent: "var(--neutralcontent)",
        "neutrallight-bg": "var(--neutrallight-bg)",
        neutralstroke: "var(--neutralstroke)",
        "neutralsub-content": "var(--neutralsub-content)",
        neutraltext: "var(--neutraltext)",
        neutralwhite: "var(--neutralwhite)",
        predictionbg: "var(--predictionbg)",
        predictioncontent: "var(--predictioncontent)",
        primarybrand: "var(--primarybrand)",
        scheduledbg: "var(--scheduledbg)",
        scheduledcontent: "var(--scheduledcontent)",
        "sec-text": "var(--sec-text)",
        successbg: "var(--successbg)",
        successcontent: "var(--successcontent)",
        successdark: "var(--successdark)",
        warningbg: "var(--warningbg)",
        warningcontent: "var(--warningcontent)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "text-base-medium": "var(--text-base-medium-font-family)",
        "text-base-regular": "var(--text-base-regular-font-family)",
        "text-base-semibold": "var(--text-base-semibold-font-family)",
        "text-heading-h5": "var(--text-heading-h5-font-family)",
        "text-SM-normal": "var(--text-SM-normal-font-family)",
        "text-small-medium": "var(--text-small-medium-font-family)",
        "text-small-regular": "var(--text-small-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
